#!/bin/bash

sudo ufw --force reset

# deny all by default
sudo ufw default deny outgoing
sudo ufw default deny incoming

# allow local traffic
sudo ufw allow out on wlo1 from 192.168.1.0/24 to 192.168.1.0/24
sudo ufw allow in on wlo1 from 192.168.1.0/24 to 192.168.1.0/24
# sudo ufw allow out on wlo1 to 192.168.1.0/24
# sudo ufw allow in on wlo1 from 192.168.1.0/24

# allow for multicasting
# Addresses above 240.0.0.0 are not multicast
# sudo ufw allow out proto udp to 224.0.0.0/4
# sudo ufw allow in proto udp from 224.0.0.0/4
sudo ufw allow out on wlo1 proto udp to 224.0.0.0/4
sudo ufw allow in on wlo1 proto udp from 224.0.0.0/4
sudo ufw allow out on wlo1 proto igmp to 224.0.0.0/4
sudo ufw allow in on wlo1 proto igmp from 224.0.0.0/4

# allow to IPs of VPN
# This does NOT work yet
# sudo ufw allow out from any to <vpn-server-ip>

# allow out to WAN only through tun interface
# sudo ufw allow out on tun0 from any to any
# sudo ufw deny in on tun0 from any to any
sudo ufw allow out on tun0 to any
sudo ufw deny in on tun0 from any

sudo ufw enable
