#!/bin/bash

sudo ufw --force reset

# deny all by default
sudo ufw default deny outgoing
sudo ufw default deny incoming

# allow local traffic
sudo ufw allow from 192.168.1.0/24

# allow to IPs of VPN
sudo ufw allow out from any to 108.59.0.37
sudo ufw allow out from any to 108.59.0.40
sudo ufw allow out from any to 185.161.200.10
sudo ufw allow out from any to 185.242.4.203
sudo ufw allow out from any to 193.148.16.227
sudo ufw allow out from any to 217.23.3.171
sudo ufw allow out from any to 217.23.3.91

# allow out only through tun interface
sudo ufw allow out on tun0 from any to any

# This should not happen as tun0 is standard, but it does
sudo ufw allow out on tun1 from any to any

# Although inherent I belive, specify
sudo ufw deny in on tun0 from any to any
sudo ufw deny in on tun1 from any to any

sudo ufw enable
